# Generated by Django 2.2.6 on 2019-11-27 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catName', models.CharField(default='unnamed', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='unnamed', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WordCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(blank=True, default='', max_length=100)),
                ('th', models.CharField(blank=True, default='', max_length=100)),
                ('ch', models.CharField(blank=True, default='', max_length=100)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Catagory')),
            ],
        ),
        migrations.AddField(
            model_name='catagory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
